### ISSUE TITLE
Great app

### ISSUE THREAD

**Issue by helincao** [dhanuravi/Employee-Attrition#1]
Very well designed and developed. Great use case of PyWebIO! I have a couple of suggestion to improve the user experience;

1) I tried the demo, everything runs smoothly! I feel mouse clicking can be reduced by using `input_group()` (https://pywebio.readthedocs.io/en/latest/input.html#pywebio.input.input_group), so users can answer multiple questions before hitting `submit` buttons. 

2) If some features have significantly higher predictive power than others, is it possible to only include questions corresponding to those features? If so, you could end up with a much shorter question list.

3) Could you also output a confidence level of your prediction if your model supports it? 

4) There is a new input method: `input.slider()`, docs: https://pywebio.readthedocs.io/en/dev/input.html#pywebio.input.slider
I feel you can use it to replace some text boxes, and improve UX. However, `slider` is only available in the dev version. But will be released in v1.3 soon.

Cheers!

**Comment by dhanuravi** [comment]
Thank you for your valuable time and suggestions. I will make use of your suggestion and will improve it.
